### ISSUE TITLE
Mismatched italics syntax causes template filter to fail sometimes

### ISSUE THREAD

**Issue by mzmcbride** [earwig/mwparserfromhell#202] opened 2018-08-30 04:16 UTC
When there's mismatched italics syntax, the `.filter_templates()` method fails to properly parse the page sometimes.

Sample script:

```python
#! /usr/bin/env python

import mwparserfromhell

def parse_text(case_text):
    parsed_page_text = mwparserfromhell.parse(case_text)
    print(len(parsed_page_text.filter_templates()))
    for template in parsed_page_text.filter_templates():
        print(template.name.strip())

case_text = """\
{{Infobox SCOTUS case
  |FullName=''[[et vir]]'
}}

'''''Hello there'''''
"""

parse_text(case_text)

case_text = """\
{{Infobox SCOTUS case
  |FullName=''[[et vir]]''
}}

'''''Hello there'''''
"""

parse_text(case_text)

case_text = """\
{{Infobox SCOTUS case
  |FullName=''[[et vir]]'
}}
"""

parse_text(case_text)
```

Of note: `  |FullName=''[[et vir]]'` is mismatched in the first case and the third case.

Current buggy output:

```
0
1
Infobox SCOTUS case
1
Infobox SCOTUS case
```

Expected output:

```
1
Infobox SCOTUS case
1
Infobox SCOTUS case
1
Infobox SCOTUS case
```

**Comment by lahwaacz** [comment] 2018-08-30 07:36
Duplicate of #40. Use `mwparserfromhell.parse()` with `skip_style_tags=True` as a workaround.

**Closed** 2018-08-31 02:46 UTC
Labels: result: duplicate
