### ISSUE TITLE
Templates with unbalanced single quotes are not parsed correctly

### ISSUE THREAD

**Issue by KOLANICH** [earwig/mwparserfromhell#176] opened 2017-05-18 14:47 UTC
for example
```
{{chembox
| Watchedfields = changed
| Reference=<ref name=Merck>''[[Merck Index]], 11th Edition, '''2623'''</ref>
}}
```

**Comment by lahwaacz** [comment] 2017-05-18 17:55
Duplicate of #40. Use `mwparserfromhell.parse()` with `skip_style_tags=True` as a workaround.

**Closed** 2017-05-18 18:52 UTC
Labels: result: duplicate
